language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q uliana-$TRAVIS_BRANCH || heroku apps:create uliana-$TRAVIS_BRANCH
- heroku git:remote -a uliana-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: b895d39d-2f54-4bfc-ac1f-2b2e0ddb9b99
  app: uliana-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
